composer.lock

theme 0.10.6

---

README.md
bootstrap.sh
composer.json
composer.lock

Also updated deploy details in the README.

Theme updates, dropping styles

---

composer.json
composer.lock

- Use the theme that supports the Swiftype crawler
- Remove the Swiftype plugin

Use the theme that supports the Swiftype crawler

---

.travis.yml

Make sure we're alerting the new app at OpsWorks.

Point travis at new production stack

---

README.md

Update the README with the command to add the private repository.

Add private repo in config

---

README.md
bootstrap.sh
composer.json
wp-config.php

@kdemi please test with a new `vagrant up` (and tell me if the README makes any sense) before merging.

Vagrant updates

---

.travis.yml

New .travis.yml for production!

Staging -> Master, Master -> Production

---

composer.json

Note that when this hits production we need to update the DB.

Updates to theme, plugins, and underlying wordpress

---

composer.json

Master -> Production

---

composer.json

Hide feeds and other dumb links.

Customization 0.13.0

---

composer.json
maintenance.html
packer/README
packer/bootstrap.sh
packer/template.json

- Add packer template and bootstrap
- Super basic maintenance page
- Theme 0.16.10 - Markup update to help with Google Analytics.

Infrastructure and theme update

---

.travis/remote.sh
composer.json
nginx/conf.d/rate_limit.conf
nginx/nginx.conf
nginx/server.d/root.conf
packer/bootstrap.sh

Also slipped the wpfront update in there.

Nginx and PHP tweaks

---

nginx/conf.d/fastcgi_cache.conf

Just moving this right into production now that it's been tested on staging.

Ignore $scheme when caching

---

composer.json
nginx/conf.d/dollar_alias.conf
nginx/server.d/robots.conf

- Update robots.txt
- Theme 0.20.3

Swiftype search updates

---

composer.json
nginx/conf.d/fastcgi_cache.conf

- property link in search
- better indexing in search without breadcrumbs, /browse, or /news
- autocomplete in search

Search advancements

---

composer.json

* hides a number of unnecessary admin items

Update non-admin roles

---

composer.json

* Adds the ability to create "Content Blocks" on department home pages.

Content Block Updates

---

.gitignore
nginx/server.d/media.conf

Reverting to allow for uploads until we've run the migration for the s3 plugin upgrade.

Media proxy revert

---

nginx/server.d/php.conf
scripts/deploy.sh
scripts/install.sh
wp-cli.yml

Modifications to install and deploy scripts to bump us up to PHP7.0.

Upgrade to PHP7

---

wp/wp-content/themes/phila.gov-theme/footer.php
wp/wp-content/themes/phila.gov-theme/partials/content-feedback-url.php

also includes mapping for new query parameters

new form url = /feedback

---

scripts/deploy.sh
scripts/update-plugins-slack.sh

Updates tell slack

---

.joia.sh
scripts/install.sh
scripts/user-env.sh

Simplified install with env handled by joia.

Env install

---

scripts/wp-config.sh
wp/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php
wp/wp-content/plugins/amazon-s3-and-cloudfront/view/domain-setting.php
wp/wp-content/plugins/amazon-s3-and-cloudfront/view/settings.php

Modifications to amazon-s3-and-cloudfront plugin (yikes!) to allow for setting of custom domain in wp-config.php.

As3cf domain

---

scripts/unison-build.sh
scripts/unison.sh

No more building unison on each new instance.

Unison binary

---

nginx/server.d/media.conf

Nginx configuration to cache media proxied from S3.

Add proxy cache for media

---

scripts/private-plugins.sh

After some testing this seems to be working fine.

WP Front User Role Editor 2.12.5

---

wp/wp-content/themes/phila.gov-theme/css/scss/_departments.scss

- Includes a transparent background to mitigate contrast / legibility issues on text overlay
**Bonus**
- Removes old alternate header overrides

Updates hero header

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_forms.scss
wp/wp-content/themes/phila.gov-theme/partials/content-page-collection.php
wp/wp-content/themes/phila.gov-theme/partials/content-page.php

* Minor updates to jotform styles

Adds before/after wysiwyg metaboxes to Pages

---

scripts/install.sh
scripts/test-instances.sh

* Set WP_DEBUG to true when spinning up test instance

Adds file to test instance deploys

---

scripts/install.sh
scripts/test-instances.sh
scripts/wp-config.sh

:stuck_out_tongue_closed_eyes:

Set debug in wp-config on test instances

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_departments.scss
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Remove JotForm metabox
* Check if module type is empty, so we don't print empty rows
* Check if wysiwyg editor is empty
* Add class name for subpage headers

Template and admin cleanup

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-department-sites.php
wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php

* Use the include/exclude plugin to manage metabox display
* Allow department authors to nest pages
* Adds the visual editor back to all department pages

Dept admin interface

---

wp/wp-content/themes/phila.gov-theme/css/scss/_service.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/js/dev/scripts.js
wp/wp-content/themes/phila.gov-theme/partials/resource-list.php

* Add data-href attribute to publication layout
* Move `.intro` styles
* Better compatibility for clickable rows

Publication hotfix

---

wp/wp-content/themes/phila.gov-theme/css/scss/_departments.scss
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Adds spacing to department templates
* Includes featured-content in department.scss

Department spacing

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/themes/phila.gov-theme/css/scss/_departments.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_news.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_wp-core.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss

* Move news styles into appropriate partial 
* No more px on wordpress core styles
* Remove extra padding on news list display

News tweaks

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/themes/phila.gov-theme/single-event_page.php

* Horizontal alignment on service update text
* Larger hit area on news/content block list view

Display tweaks

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-event-pages.php
wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js
wp/wp-content/themes/phila.gov-theme/single-event_page.php

- Alter validation behavior for events pages
- Limit displayed service updates to 4

Service changes

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-event-pages.php
wp/wp-content/themes/phila.gov-theme/single-event_page.php

- Update service update message text char limit from 100 to 95
- Adjust heading levels

Event hotfix

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-event-pages.php
wp/wp-content/themes/phila.gov-theme/css/scss/_events.scss
wp/wp-content/themes/phila.gov-theme/single-event_page.php

This PR creates a "Call to Action" metabox to replace the custom markup area currently being used on Event pages.

"Call to Action" panel

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_events.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/single-event_page.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Extrapolate call to action panel styles and markup into department page templates
* Standardize pattern

Call to action panel for department home pages

---

wp/wp-content/themes/phila.gov-theme/css/scss/_call-to-action.scss

- Override style defined in _calendar.scss
- Add margins when CTA panels are in mobile view

Style Adjustments

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php

* Add ability to check existence of homepage editor role for more granular editing options.

Homepage editor

---

wp/wp-content/themes/phila.gov-theme/functions.php

* Add open graph metadata for all pages:
* title
* type
* image
* url
* site_name
* description
* Add twitter card type

Open graph tags

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php

* Remove extra `equal` class being applied to news rendering

Remove extra equal class

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/header.php

* slugs_list was created for GTA, but we prefer sentence case names.

Swap unused slugs for nice names

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-department-homepage.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-get-involved.php
wp/wp-content/themes/phila.gov-theme/partials/resource-list.php

- Adds some comments
- Set max clone for featured programs and initiatives / custom text multi
- Removes extra elements that were keeping pages from validating.

MOE cleanup

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-templates.php
wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php
wp/wp-content/themes/phila.gov-theme/templates/page-collection.php

Updates include:
* Handle case where tax rate might need to be paragraph text
* Correct front-end and admin interface labels
* Allow Pages to use the template

Tax template updates

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Adds an option to include an address in the "How to pay" free form content area
* Addresses get appropriate vcard markup
* Title fields for this section are not required, allowing a user to enter a title, content & immedately follow with an address

Tax detail address field

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Corrects rendering of monetary units
* Ensures an intro, stepped content or both will render regardless of the existence of either fields

Tax detail tweaks

---

wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Validation on entry of certain fields
* Corrects display typo

Tax hotfix

---

wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

Add echo for permalink display

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_panel.scss
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

Includes minor tweaks to front-end rendering and swaps a textarea for a wysiwyg editor for maximum flexibility.

Tax layout tweaks

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/content-service-default.php
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php
wp/wp-content/themes/phila.gov-theme/templates/page-collection.php

* Adds clonable wysiwyg options to "Default" service page content
* Includes ability to choose from heading levels 3 or lower when entering wysiwyg content 
* Updates appropriate fields to use heading selection
* Minor clean up

Default service template

---

wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Checks for values in more fields before deciding to print or not to print to the screen

Add OR statements for discounts vs. exemptions & cost vs. late fees

---

wp/wp-admin/about.php
wp/wp-admin/includes/class-wp-upgrader.php
wp/wp-admin/includes/media.php
wp/wp-includes/version.php

Details here: https://codex.wordpress.org/Version_4.5.4

Update to version 4.5.4

---

wp/wp-content/themes/phila.gov-theme/css/scss/beta/_feedback.scss
wp/wp-content/themes/phila.gov-theme/footer.php
wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/js/dev/scripts.js
wp/wp-content/themes/phila.gov-theme/partials/content-beta-alert.php
wp/wp-content/themes/phila.gov-theme/partials/content-feedback.php
wp/wp-content/themes/phila.gov-theme/partials/content-service-mega-menu.php

- Chrome Vox unable to read megamenu items
- Voiceover on mobile failing to read drilldown menu items
- Inability to tab through the mobile drilldown
- Ambiguous links for screenreaders in the beta-alert and megafooter
- Tab order of the header
- Inability to tab through feedback forms
- blue text on blue backgrounds
- white text on green/yellow/red backgrounds
- blue text on light gray backgrounds

Accessibility corrections

---

wp/wp-content/themes/phila.gov-theme/css/scss/beta/_home.scss
wp/wp-content/themes/phila.gov-theme/front-page.php

Adds a frequently requested voting information link to the homepage for election season. To be removed after November 8th.

Voting link

---

.travis.yml

Not quite ready to merge -- need to coordinate w/Day1 on testing, but my hypothesis is that this will work. Note the env vars are at https://travis-ci.org/CityOfPhiladelphia/phila.gov/settings

Use codedeploy settings in .travis.yml

---

wp/wp-content/themes/phila.gov-theme/front-page.php

Alters a comment on the front page:
From:        End Beta.phila.gov Message 
To:      End beta.phila.gov message

Beta travis deploy

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-contact-us.php

* Minor adjustments to contact us template

Template tweaks

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-service-update-pages.php
wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/content-service-updates.php

This addresses service update clarifications to the admin. 
Additional functionality:
* Ability to mark service update links as external instead of assuming them as such

Admin clean up

---

wp/wp-content/themes/phila.gov-theme/css/scss/_staff-directory.scss

Start from white instead of transparent

---

scripts/install.sh

- Prevents this horrible pink screen from appearing

Don't stop install for user input

---

scripts/install.sh

The deploy failed with the change below. Rolling back for now.

Rollback dist-upgrade

---

wp/wp-content/themes/phila.gov-theme/footer.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-connect.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

* This institutes the agreed-upon convention for passing data to our analytics product. In the form of `data-analytics="identifier"`.

Analytics updates

---

wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php

* Leadership heading should appear on one page templates

Correct staff display

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/header.php

* Pass more data to analytics including last modified & template type

Data layer modifications

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php

* Allow users to set custom icons on one page department sites
* Increase CTA limit from 3 to 4

Call to action 

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

- Actually render the see all link

Render see all link

---

wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php

* Always show all staff members

Show all staff

---

wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php

Remove var_dump

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-homepage-full-width-cta.php

* Don't render connect rows that don't have content
* Clean up rendering of full-width cta

Connect box

---

wp/wp-content/themes/phila.gov-theme/css/scss/_hero-header.scss
wp/wp-content/themes/phila.gov-theme/single-department_page.php

* Correct photo credit display & remove class name change

Photo credit hotfix

---

wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Move v2 homepage modules to opening if statement to prevent rendering duplication (specifically in the case of staff profiles)
* Update comments to better reflect what is happening

On-site department template tweak

---

wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Corrects issue where certain template content was repeated on v2 homepages

Correct v2 template display

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/blogs.php
wp/wp-content/themes/phila.gov-theme/css/scss/_departments.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-row-two.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-featured.php
wp/wp-content/themes/phila.gov-theme/single-department_page.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* New component for "Featured page" area in v2 department homepages.
* Streamline check for v2 template application. If the department's homepage is set to v2, then all the child pages should also use a v2 rendering. 
* Refactors department hero typography rendering into function & adds new phrases.
* Add full-width blog row option.
* Adds YouTube to connect box. 
* Changes "All staff" label to more generic "Staff" label. 
* Adds `editor` role to all `administrator` fields. 
* Ensure dates appear on news/blogs displays.

Department updates

---

wp/wp-content/themes/phila.gov-theme/functions.php

Ensure department title is rendered if there is no matching phrase

---

scripts/install.sh

Remove dist-upgrade, thanks @gsf.

Remove unneeded dist-upgrade

---

wp/wp-content/themes/phila.gov-theme/css/scss/beta/_utils.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/partials/content-single-post.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-row-one.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

* Prevents blog images from spilling out of their container 
* Increases width of Connect box
* Removes "social" column if no staff has social.

Layout fix

---

wp/wp-content/themes/phila.gov-theme/css/scss/beta/_buttons.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/content-connect.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-custom-text-multi.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-department-homepage.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-list-items.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-row-one.php

* Adjust button height 
* Adjust column ratio on all templates for consistency

Layout tweak

---

scripts/private-plugins.sh

* Updates metabox plugins to allow us to leverage new functionality

Plugin updates

---

wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/partials/content-single-news.php

* Re-adds the phila-thumb max-width.
* Cleans up spacing.

News hotfix

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

Adds option for full-width press releases on department homepages.

Press releases

---

wp/wp-content/themes/phila.gov-theme/css/scss/_hero-header.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/js/dev/scripts.js
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php

* Increase font size of standard department name intro
* Better error handling on MailChimp submissions
* Add "Philadelphia" to hero header small text function
* Don't hide empty table cells with CSS, it's too fragile. Instead, check for empty columns with JS and hide when found.

Landing page tweaks

---

nginx/nginx.conf

Adjust gzip settings to help with page load times

---

nginx/nginx.conf

Reverts CityOfPhiladelphia/phila.gov#455
This seems to make things worse.  ¯\_(ツ)_/¯

Revert "Adjust gzip settings to help with page load times"

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php

* Add REST API support to services (woot!)
* Add author to most other CPTs

Cpt updates

---

wp/wp-content/themes/phila.gov-theme/functions.php

Add target phrase

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php

This one's for you @michaelck. Although, I'm not certain how immediately useful it will be.

Add service updates to rest API

---

nginx/server.d/climatechangeisreal.conf

* Redirects /climatechangeisreal to github repo of the same name.

Add server settings

---

scripts/predeploy.sh

This should correct the interactive screen during predeploy.
https://console.aws.amazon.com/codedeploy/home?region=us-east-1#/deployments/d-S0RJHP7VM/instances/i-c7e8dfd1/events/BeforeInstall/logs

Align install and predeploy scripts

---

scripts/predeploy.sh

Correct export command & add sudo to apt-get upgrade

Use export, add sudo

---

wp/wp-content/themes/phila.gov-theme/functions.php

* Add `City of Philadelphia`
* Ensure `Philadelphia` appears before "Department", etc. 
* Add space after `Philadelphia` in case it appears at the end of a title...

Add edge cases

---

wp/wp-content/plugins/phila.gov-customization/public/add-headers.php

Allow more resources to be gzipped.

Accept gzip

---

wp/wp-content/themes/phila.gov-theme/package.json

Helps to build all your resources.

Actually build the js

---

wp/wp-content/themes/phila.gov-theme/package.json

Ensure fonts directory is getting copied over on deploy.

Add fonts to prebuild

---

wp/wp-content/themes/phila.gov-theme/js/dependencies/jquery.swiftype.autocomplete.js
wp/wp-content/themes/phila.gov-theme/js/dependencies/jquery.swiftype.search.js

Don't scope jQuery

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/footer.php

* Provides option to include per-page script tags, if necessary.

Footer content

---

wp/wp-content/plugins/phila.gov-customization/admin/css/admin-department-author.css
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

* Hide the tag div, which looks to have been changed to an ID instead of a class name. 
* Update dependences.

Tags hotfix

---

wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/content-wip.php

* Corrects cookie setting by pointing to non-redirected URL. 
* Uglify 3.1.0

Redirect hotfix

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php
wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js
wp/wp-content/plugins/restrict-categories/restrict-categories.php

* Ensure that users with all department access, or multi department access don't have a category automatically selected. 
* Correct search query that was breaking role overrides in the Restrict Categories plugin. 
* Also clean up file.

Role fixes

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/rest-additions.php

* Exposes department pages to the rest API and provides department connect box information via `contact_information`

Department rest

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/plugins/phila.gov-customization/admin/rest-additions.php

* Adds metabox for department code & exposes it through WP API

Add department code meta

---

wp/wp-content/plugins/phila.gov-customization/admin/admin-ui.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php

* Allow private pages to be selected in nav menu & department homepage service area.

Private pages

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/press-releases.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/user_templates/homepage_v2.php

Echo shortcode and wrap news/press releases with enclosing div.

Bdolly develop

---

wp/wp-admin/about.php
wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-calendar-helper.php
wp/wp-content/plugins/phila.gov-customization/admin/rest-additions.php
wp/wp-includes/formatting.php
wp/wp-includes/post.php
wp/wp-includes/version.php
wp/wp-includes/wp-db.php

* Update WP
* Fix accidental var_dump
* Add quotes to string

Update to WP 4.8.3

---

wp/wp-content/plugins/phila.gov-customization/public/rewrite-rules.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/user_templates/homepage_v2.php

* Removes full width news option & cleans up old rewrite rules

News clean up

---

wp/wp-content/themes/phila.gov-theme/css/scss/_table.scss
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Archives.vue

Remove the `.clickable-row` class that was interfering with the vuejs click event.

Correct clickable link

---

wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/posts/announcements-grid.php
wp/wp-content/themes/phila.gov-theme/partials/posts/content-card.php
wp/wp-content/themes/phila.gov-theme/partials/posts/content-list-image.php
wp/wp-content/themes/phila.gov-theme/partials/posts/content-related.php
wp/wp-content/themes/phila.gov-theme/partials/posts/press-release-grid.php
wp/wp-content/themes/phila.gov-theme/templates/the-latest.php

* Fixes related item display on posts where image is too small. 
* Adds deep linking to announcements. 
* Corrects heading level on the latest display.
* Removes category call on related press releases.
* Update vuejs datepicker to 0.9.20.

Layout hotfix

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/.gitignore
wp/wp-content/themes/phila.gov-theme/css/scss/_post.scss
wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/inc/breadcrumbs.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/posts/action-guide-content.php
wp/wp-content/themes/phila.gov-theme/partials/posts/announcements-grid.php
wp/wp-content/themes/phila.gov-theme/partials/posts/content-card.php
wp/wp-content/themes/phila.gov-theme/partials/posts/post-end-cta.php
wp/wp-content/themes/phila.gov-theme/templates/single-post.php

* Hide featured images on action guides
* Corrects breadcrumbs
* Adds intro to action guides
* Clean up announcements rendering  
* Adds announcements to homepage
* Handle empty fields better
* Force users to "the latest" admin area, in the event they had old post types bookmarked
* Show end date in announcements view
* Handful of dependency updates

Announcement rendering + admin clean up

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-item-meta-desc.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php
wp/wp-content/themes/phila.gov-theme/archive-document.php
wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Publications.vue
wp/wp-content/themes/phila.gov-theme/js/vuesrc/main.js

* Moves announcements higher up on the homepage
* Increases tweet sharing text length

Layout updates

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-item-meta-desc.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php
wp/wp-content/themes/phila.gov-theme/css/scss/_service-updates.scss
wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/partials/content-service-updates.php

* Ensures equal spacing on beta homepage between rows
* Adds to maximum character count for social intents
* Moves announcements up on homepage

Homepage clean up

---

wp/wp-content/plugins/phila.gov-customization/admin/admin-ui.php
wp/wp-content/plugins/phila.gov-customization/admin/css/admin.css
wp/wp-content/plugins/phila.gov-customization/admin/js/admin-edit.post.js
wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js

Fixing trello issue https://trello.com/c/608SjHPu/233-since-we-removed-attachment-pages-also-remove-admin-option-to-view-them

Two trello issues fixed.

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-custom-phone.php

Trello fix: Contact us template - Clonable phone fields not being cleared on clone
Put this fix on its own branch.

quick fix to phone field

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/tiny-mce.php

Added as result of request for footnotes on history pages of PPR project.

Add super/subscript

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php

Allow document pages of any type to appear in forms + docs section

---

wp/wp-content/plugins/phila.gov-customization/admin/css/admin.css
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/layout.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/document-finder.php

Reimplements document tables template. Allows user to add multiple tables to a page.

Document finder

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_sticky-nav.scss
wp/wp-content/themes/phila.gov-theme/partials/content-heading-groups.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-one-quarter.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action-guide-content.php
wp/wp-content/themes/phila.gov-theme/partials/services/content-tax-detail.php
wp/wp-content/themes/phila.gov-theme/partials/stepped-content.php

A number of minor improvements. 
* Corrects action guide hover color
* Pads action guide content
* Allows content authors to include stepped content template with a heading group.
* Ads ids for anchor links to all 1/4 heading templates.

General fixes

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/posts/announcements-grid.php

* Saves and compares unix values.

Announcement fix

---

wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/content-additional.php
wp/wp-content/themes/phila.gov-theme/partials/content-heading-groups.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action-guide-content.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action-guide-title.php
wp/wp-content/themes/phila.gov-theme/partials/services/content-tax-detail.php

* Corrects display of stepped content on service pages. 
* Reduces size of headings on service pages. 
* Update dependencies.

Service pages

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/programs-initiatives/class-phila-gov-templates.php
wp/wp-content/themes/phila.gov-theme/css/scss/modules/_hero-half.scss
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Events.vue
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/programs/header.php
wp/wp-content/themes/phila.gov-theme/single-programs.php

* Apply before/after wysiwyg content to program pages
* Add program owner logo + help text
* Dependency updates
* Remove date restrictions on events

Program page tweaks

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-taxonomies.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/plugins/phila.gov-customization/admin/programs-initiatives/class-phila-gov-templates.php
wp/wp-content/themes/phila.gov-theme/css/scss/_linked-image-grid.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_things-to-do.scss
wp/wp-content/themes/phila.gov-theme/js/dev/search.js
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_linked_image_grid.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-feat-activity-card.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/programs-initiatives-grid.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-things-to-do.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/photo-callout-block.php
wp/wp-content/themes/phila.gov-theme/single-programs.php

* Prepares service content for appearance in Program + init landing page related content section. 
* Adds "off-site" program template. Redirect to the location of the program page if off-site template is selected.
* Includes a number of small updates to Things to do display and admin interface.

Programs landing

---

wp/wp-content/themes/phila.gov-theme/partials/programs/image-list.php

Don't center when only one image is displayed

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-taxonomies.php
wp/wp-content/plugins/phila.gov-customization/index.php
wp/wp-content/plugins/phila.gov-customization/public/class-phila-programs-controller.php
wp/wp-content/themes/phila.gov-theme/archive-programs.php
wp/wp-content/themes/phila.gov-theme/css/scss/_accordion.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/js/dev/collapsible-div.js
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Programs.vue
wp/wp-content/themes/phila.gov-theme/js/vuesrc/main.js
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

* Registers a vue.js app for programs and initiatives landing page. 
* Pulls in related program content where appropriate.

Programs landing page

---

wp/wp-content/plugins/phila.gov-customization/index.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/modal.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

Creates modal shortcode with id + clickable button text attributes. Allows HTML. 
Update dependencies.

Modal shortcode

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js

Turns out this is too restrictive.

Remove email address requirement

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

Document meta is not saved correctly when duplicated. This is a temporary fix until further investigation can be done.

Remove duplicate and edit from document pages

---

wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

https://babeljs.io/docs/usage/polyfill/

Save as dependency not devDependency

---

nginx/nginx.conf
nginx/server.d/00_x_frame_options.conf

XFO header

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-menu.php
wp/wp-content/plugins/phila.gov-customization/admin/css/admin-department-author.css
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/document-finder.php

Minor tweaks:
* Hide add new buttons unless user is in a "creator" role
* Clean up things to do admin interface
* Allow cloning/removal of resource lists + document tables
* Add jump links to tables on document tables template so users don't try and add markup to the text fields to make their down anchor tags

Editor updates

---

wp/wp-content/plugins/phila.gov-customization/index.php
wp/wp-content/plugins/phila.gov-customization/public/class-phila-last-updated-controller.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

Prep for static site generation. 
Endpoint for all post types lives at: `/wp-json/last-updated/v1/all`
Accepts query param in the format of:`?timestamp="Y-m-d H:i:s"`
E.g.: `?timestamp=2018-04-16%2014:30:35`

Last updated endpoint

---

wp/wp-content/themes/phila.gov-theme/css/scss/_sticky-nav.scss
wp/wp-content/themes/phila.gov-theme/css/scss/modules/_event-spotlight.scss
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/featured-events.php

Correct time display, clean up rendering.

Event spotlight cleanup

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-taxonomies.php
wp/wp-content/plugins/phila.gov-customization/admin/event-spotlight/templates/class-phila-gov-spotlight.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/header.php
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/rows.php
wp/wp-content/themes/phila.gov-theme/partials/posts/post-grid.php

* Users can now assign an event tag to posts, specifically and only for use in the "Event spotlight". 👍

Event tags

---

wp/wp-content/themes/phila.gov-theme/js/vuesrc/Events.vue

Add query param to prevent events added later than others from not appearing.

Google API call adjustment

---

wp/wp-content/plugins/phila.gov-customization/public/class-phila-last-updated-controller.php

* Add updated_at field
* Ensure exact timestamp matched are included in the payload
* Match on `date_modified` column instead of `post_date`

Updated at

---

wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/js/dev/search.js

Attempt to use a different type of Swiftype tag.

Use tag instead of type

---

wp/wp-content/plugins/phila.gov-customization/public/class-phila-document-controller.php
wp/wp-content/plugins/phila.gov-customization/public/class-phila-posts-controller.php
wp/wp-content/plugins/phila.gov-customization/public/class-phila-programs-controller.php

This intentionally omits the "last-updated" controller.

Make api links relative

---

scripts/predeploy.sh

Move env var assignment to user_data

---

wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/featured-events.php
wp/wp-content/themes/phila.gov-theme/style.css

Don't force a date/time on featured event blocks.

Fixes/spotlight - 0.23.1

---

wp/wp-content/themes/phila.gov-theme/css/temp-disable-login.css
wp/wp-content/themes/phila.gov-theme/functions.php

Temporarily prevent editors from logging in.

Disable login

---

wp/wp-content/plugins/phila.gov-customization/admin/css/admin.css
wp/wp-content/plugins/phila.gov-customization/admin/departments/class-phila-gov-department-register-templates.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-admin-templates.php

* Prep for services alternate title feature. 
* In admin, hide items on load. 
* Add id for department template select to appear in admin columns.

Services alternate title

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/archive-service_page.php

Remove contextual page and replace with hide children.

Service tweaks

---

wp/wp-content/plugins/phila.gov-customization/public/hostname-redirect.php
wp/wp-content/themes/phila.gov-theme/functions.php

* Addresses missing vars for local development

Add checks for variables that might not be set for local dev

---

wp/wp-content/plugins/phl-aqi/includes/aqi-template.php
wp/wp-content/plugins/phl-aqi/includes/js/phl-aqi.js

Changed the plugin animation to css opacity, since display none and block with javascript was causing issues.

Aqi plugin animation

---

scripts/private-plugins.sh
wp/wp-content/plugins/meta-box/inc/fields/taxonomy-advanced.php
wp/wp-content/plugins/meta-box/inc/fields/taxonomy.php
wp/wp-content/plugins/meta-box/inc/loader.php
wp/wp-content/plugins/meta-box/inc/meta-box.php
wp/wp-content/plugins/meta-box/inc/storages/base.php
wp/wp-content/plugins/meta-box/meta-box.php
wp/wp-content/plugins/meta-box/readme.txt

* Metabox 4.15.7
* Metabox Conditional logic 1.6.3
* Metabox group 1.2.17
These updates should introduce significant speed improvements in the admin interface.

Metabox updates

---

wp/wp-content/plugins/phl-aqi/includes/class-phl-aqi.php

Also includes some file formatting.

Use second param from endpoint to display PM2 number

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-all-services.php

Use alternate title and add in-page nav

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-all-services.php

Isset returning true, which is not a link.

Remove isset

---

wp/wp-content/themes/phila.gov-theme/js/dev/search-sort-tables.js
wp/wp-content/themes/phila.gov-theme/templates/documents.php

Create specific class for document tables

Document pages don't get pagination

---

wp/wp-content/plugins/phila.gov-customization/admin/departments/templates/class-phila-gov-collection-page.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/collection-page.php

Ready to merge on Monday, 2/8.

Add expand collapse on free-text collection pages

---

wp/wp-content/themes/phila.gov-theme/css/scss/pages/_programs-initiatives.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/homepage_programs.php
wp/wp-content/themes/phila.gov-theme/single-programs.php
wp/wp-content/themes/phila.gov-theme/templates/single-off-site.php

This has the added benefit of preventing the scraper from scraping 302s.

Program transition page 

---

wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/single-service_page.php

A few tweaks to ensure proper implementation.

Analytics adjustments

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

Create repeatable phone number field for connect box.

Add new field for multiple phone numbers

---

wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/card.php

Prevent query from interfering with other components

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-select-options.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/content-modified.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_staff_directory_listing.php
wp/wp-content/themes/phila.gov-theme/partials/posts/post-grid.php
wp/wp-content/themes/phila.gov-theme/partials/posts/press-release-grid.php

Adds the ability to include staff members as part of the subpage with association template.

Subpage association with staff

---

wp/wp-content/plugins/restrict-categories/js/restrict-categories.js
wp/wp-content/plugins/restrict-categories/readme.txt
wp/wp-content/plugins/restrict-categories/restrict-categories.php
wp/wp-content/plugins/restrict-categories/uninstall.php

The update broke all the assigned categories. YAY

Downgrade plugin

---

wp/wp-content/themes/phila.gov-theme/js/dev/hide-empty-table.js
wp/wp-content/themes/phila.gov-theme/js/dev/search-sort-tables.js
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/document-finder.php
wp/wp-content/themes/phila.gov-theme/templates/documents.php

- Show six files instead of 3
- Show descriptions if they exist
- Ensure columns with no data are hidden

Doc finder adjustments

---

wp/wp-content/themes/phila.gov-theme/single-programs.php

TODO: Turn this into a template. This is a temporary solution.

Fix child index

---

wp/wp-content/plugins/phila.gov-customization/public/removals.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/package-lock.json

Deregister wp embed

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-vue-app.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/header.php
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/official-info.php
wp/wp-content/themes/phila.gov-theme/partials/event-spotlight/rows.php
wp/wp-content/themes/phila.gov-theme/partials/services/content-vue-app.php

- Registers before/after wysiwyg for spotlight pages

Vue app id corrected for service pages

---

wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-posts.php

Enables us to start using this in "the latest" vue application.

Add translated languages to posts endpoint

---

wp/wp-content/plugins/phila.gov-customization/admin/departments/class-phila-gov-department-register-templates.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

Allows department subpages to use more flexible "Page content" meta boxes.

Add Repeating rows template

---

wp/wp-content/themes/phila.gov-theme/partials/global/analytics.php

Removes duplicate data layers which can cause problems.

Adjust dataLayer to add page language

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php
wp/wp-content/plugins/phila.gov-customization/admin/css/group-adder.css
wp/wp-content/plugins/phila.gov-customization/public/class-phila-gov-site-wide-alert-rendering.php

Non-admins and editors can't create repeating sets of content though the Page Content builder. This role will allow those users to be able to add and remove sections.

Refine permissions

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/service-page/class-phila-gov-service-register-templates.php
wp/wp-content/themes/phila.gov-theme/partials/content-additional.php
wp/wp-content/themes/phila.gov-theme/partials/content-custom-additional.php

I'd like to revisit this. It seems problematic that there are two places that need to be updated in order for this field to render, for the time being, though, this is fine.

Add wysiwyg field to forms + instructions

---

wp/wp-content/themes/phila.gov-theme/partials/programs/header.php

Fixes header and brings master up to date.

Header update

---

wp/wp-content/themes/phila.gov-theme/partials/departments/content-get-involved.php
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_module_row_1.php
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_staff_directory_loop.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/full-width-call-to-action.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/homepage_timeline.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/our-services.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/photo-callout.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action_guide_v2/components/repeater-wysiwyg.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action_guide_v2/components/single-wysiwyg.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action_guide_v2/components/stepped-content-wrapper.php
wp/wp-content/themes/phila.gov-theme/partials/posts/action_guide_v2/components/timeline-content.php
wp/wp-content/themes/phila.gov-theme/partials/posts/post-translated-langs-see-all.php
wp/wp-content/themes/phila.gov-theme/partials/posts/press-release-translated-langs-see-all.php
wp/wp-content/themes/phila.gov-theme/partials/programs/image-list.php
wp/wp-content/themes/phila.gov-theme/partials/programs/location-list.php

Added ID's from either the input title or the default title for sections in program + department homepages

Homepage jumplinks

---

wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/partials/content-custom-additional.php

This corrects a div opening/closing outside of an if statement, causing an extra closing div and breaking a service page layout.

Service fixes

---

wp/wp-content/themes/phila.gov-theme/css/scss/_alerts.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_label.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_panel.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_sticky-nav.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_table.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_typography.scss
wp/wp-content/themes/phila.gov-theme/css/scss/base.scss
wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss
wp/wp-content/themes/phila.gov-theme/css/scss/modules/_hero-header.scss
wp/wp-content/themes/phila.gov-theme/css/scss/pages/_documents.scss
wp/wp-content/themes/phila.gov-theme/css/scss/pages/_guides.scss
wp/wp-content/themes/phila.gov-theme/footer.php
wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/partials/content-feedback.php

Increases most fonts to base 16. Adjusts other areas where necessary.

Typography main

---

wp/wp-content/themes/phila.gov-theme/css/scss/pages/_post.scss

Active on this page https://test-admin.phila.gov/2020-07-07-keeping-campers-safe-at-parks-rec-sites-this-summer/#

Translation bar new font

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-documents.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/templates/single-post.php

Blog images with optional captions and credits

Blog images 2

---

wp/wp-content/themes/phila.gov-theme/css/scss/_typography.scss

Pages to check 
https://localhost:19107/services/business-self-employment/report-possible-fraud-waste-or-other-issues-on-contracts/ 
https://localhost:19107/services/business-self-employment/support-for-businesses/find-loans-through-the-philadelphia-business-lending-network/

Fix stub page h3 spacing & last-of-type lists

---

wp/wp-content/themes/phila.gov-theme/css/scss/_lightbox.scss

This should fix backgrounds being scrollable when modals are open.

Remove old custom css

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-custom-unit.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/photo-callout.php

This should remove the warnings we were seeing in local dev on php 7.4.

Php warnings

---

wp/wp-content/themes/phila.gov-theme/css/scss/_typography.scss

Removes extra padding from services cards on stub pages.

Fixes service spacing on stub pages

---

scripts/wp-config.sh

Updates the encoding for the servers database to enable plugins to be installed properly.

update db encoding

---

scripts/wp-config.sh

Adds dbcharset using wpcli during deploy

Dbcharset update

---

wp/wp-content/themes/phila.gov-theme/partials/content-additional.php

https://www.wrike.com/open.htm?id=929360575

Changed closing div tag location

---

wp/wp-content/themes/phila.gov-theme/css/scss/_layout.scss
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/templates/single-post.php

https://www.wrike.com/workspace.htm?acc=2747306#folder/884002094/board?overlayEntityId=865536800&sortOrder=10&spaceId=453350584&viewId=81744461

Last updated

---

wp/wp-content/themes/phila.gov-theme/css/scss/_typography.scss
wp/wp-content/themes/phila.gov-theme/partials/content-custom-prereq-row.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-feat-activity-card.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-feat-locationType-card.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-loader-svg.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/department-hero.php

Removes new line from certain files, addes comments, removes old blank file.

Php new line

---

wp/wp-content/themes/phila.gov-theme/css/scss/_typography.scss
wp/wp-content/themes/phila.gov-theme/partials/content-custom-prereq-row.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-feat-activity-card.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-feat-locationType-card.php
wp/wp-content/themes/phila.gov-theme/partials/departments/ppr/ppr-loader-svg.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/department-hero.php

Also cleans up some older files

Remove extra line at beginning of php files

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-posts.php

https://www.wrike.com/open.htm?id=849388266
confirmed lang selection is retained after moving to a dedicated container

Archived posts endpoints

---

wp/wp-content/plugins/phila.gov-customization/public/class-phila-gov-site-wide-alert-rendering.php

https://www.wrike.com/open.htm?id=961900822

Banner text change

---

scripts/private-plugins.sh
wp/wp-content/plugins/better-search-replace/README.txt
wp/wp-content/plugins/better-search-replace/better-search-replace.php
wp/wp-content/plugins/better-search-replace/includes/class-bsr-ajax.php
wp/wp-content/plugins/better-search-replace/includes/class-bsr-db.php

https://www.wrike.com/open.htm?id=961939010

Update plugins 2022 09 14

---

wp/wp-content/themes/phila.gov-theme/css/scss/_expandable.scss
wp/wp-content/themes/phila.gov-theme/partials/services/content-default-v2.php

https://www.wrike.com/open.htm?id=952500811

Cost-Cards

---

wp/wp-content/themes/phila.gov-theme/css/scss/_layout.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_sticky-nav.scss
wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss
wp/wp-content/themes/phila.gov-theme/css/scss/pages/_post.scss

This increases the max width of our base template to 1440px, or 90rem. 
https://www.wrike.com/open.htm?id=982469662

Larger width

---

wp/wp-content/themes/phila.gov-theme/css/scss/_panel.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_call_to_action_multi.php

https://www.wrike.com/workspace.htm?acc=2747306#folder/990711801/board?overlayEntityId=884724421&sortOrder=10&spaceId=453350584&viewId=118195226

Fix resources list

---

wp/wp-content/themes/phila.gov-theme/partials/content-additional.php

https://www.wrike.com/open.htm?id=968099021

topic page/related content wrapping

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-taxonomy-meta.php

added dept code to taxonomy with mild wp-admin formatting 
https://www.wrike.com/open.htm?id=1005820212

add dept code

---

wp/wp-content/themes/phila.gov-theme/css/scss/_block-quotes.scss
wp/wp-content/themes/phila.gov-theme/css/scss/base.scss
wp/wp-content/themes/phila.gov-theme/partials/posts/block-quote.php
wp/wp-content/themes/phila.gov-theme/partials/posts/call-to-action.php
wp/wp-content/themes/phila.gov-theme/shortcodes/block-quote.php

https://www.wrike.com/open.htm?id=978336851

block quote creation

---

wp/wp-content/themes/phila.gov-theme/partials/content-additional.php

https://www.wrike.com/open.htm?id=968099021

Topic page wrapping

---

wp/wp-content/themes/phila.gov-theme/footer.php

https://www.wrike.com/open.htm?id=995758892

Update footer links

---

wp/wp-content/themes/phila.gov-theme/footer.php

https://www.wrike.com/open.htm?id=995758892

footer links updated

---

wp/wp-content/themes/phila.gov-theme/partials/services/content-topic-page.php

https://www.wrike.com/workspace.htm?acc=2747306#/task-view?id=923126377&pid=884002094&cid=453350584

Make topic pages two columns

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php

https://www.wrike.com/open.htm?id=1023894698

Remove feature functionality

---

wp/wp-content/themes/phila.gov-theme/partials/posts/content-related.php

https://www.wrike.com/open.htm?id=925860750

related content updated to related post

---

wp/wp-content/plugins/phila.gov-customization/admin/translations.php

null check for endpoint on translation submission

adds null check for translation submit

---

wp/wp-content/themes/phila.gov-theme/css/scss/_block-quotes.scss

https://www.wrike.com/open.htm?id=1033082769

quote formatted to times new roman

---

wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/js/dev/phila-gov.js

- Deleted translated publications list element
- Updated Google Translate default text from "Select Language" to "More Languages"

removes translated publications

---

wp/wp-content/themes/phila.gov-theme/footer.php

https://www.wrike.com/open.htm?id=1060928303

right to know link change

---

wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss
wp/wp-content/themes/phila.gov-theme/header.php
wp/wp-content/themes/phila.gov-theme/js/dev/phila-gov.js

https://www.wrike.com/workspace.htm?acc=2747306#folder/884002094/board?overlayEntityId=1049353633&sortOrder=10&spaceId=453350584&viewId=81744461
- On actual mobile, the translation menu requires a double tap
- Dropdown triggers on desktop when languages are selected

Disable hover ipad

---

appspec.yml
scripts/clean-machine.sh
scripts/predeploy.sh

https://www.wrike.com/open.htm?id=1072837817

Ubuntu cleaner

---

wp/wp-content/themes/phila.gov-theme/js/dev/translations.js

https://www.wrike.com/open.htm?id=1140643331
- ?? for chinese on spanish
- spanish should read espanol on all language options

update translation text

---

wp/wp-content/themes/phila.gov-theme/shortcodes/embedded-form.php

https://www.wrike.com/open.htm?id=1083066857

embedded form shortcode creation

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-select-options.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_button.scss
wp/wp-content/themes/phila.gov-theme/css/scss/_lightbox.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/services/content-phila-modal.php

https://www.wrike.com/open.htm?id=1129623387

Default 2020 modal

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-taxonomies.php
wp/wp-content/plugins/phila.gov-customization/admin/event-spotlight/class-phila-gov-cpt-event-spotlight.php
wp/wp-content/plugins/phila.gov-customization/index.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-documents.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-posts.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-programs.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/class-phila-staff-members.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/v2/class-phila-announcements-v2.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/v2/class-phila-posts-v2.php
wp/wp-content/plugins/phila.gov-customization/public/controllers/v2/class-phila-spotlights-v2.php
wp/wp-content/themes/phila.gov-theme/functions.php

ex endpoint http://philagov.local/wp-json/wp/v2/posts/245645

extend post rest api

---

wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss
wp/wp-content/themes/phila.gov-theme/header.php

https://www.wrike.com/open.htm?id=1174508996

hidden languages added to dropdown menu

---

wp/wp-content/plugins/phila.gov-customization/index.php

Removal of class-phila-site-wide-alerts-v2 from index.php

file removed

---

wp/wp-content/plugins/phila.gov-customization/admin/settings/phila-gov-settings.php

https://www.wrike.com/open.htm?id=1141744271
added desc to wysiwig to inform 170 char limit

Trash & Recylcing update character limit

---

wp/wp-content/plugins/phila.gov-customization/admin/departments/templates/class-phila-gov-collection-page.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/departments/phila_staff_directory_listing.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/board_commission_member_list.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/collection-page.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/member_list.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/user_templates/homepage_v2.php

https://www.wrike.com/open.htm?id=1091027407

Program pages staff members component 2 main

---

wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss

https://www.wrike.com/open.htm?id=1186667846

enable languages in header

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/member_list.php

https://www.wrike.com/open.htm?id=1203531008

component fixed on homepage_v2

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/services/content-topic-page.php

https://www.wrike.com/open.htm?id=977135713

wysiwyg added

---

wp/wp-content/themes/phila.gov-theme/inc/resource-list-switch.php

https://www.wrike.com/open.htm?id=1143895758

resource list switch function fixed

---

wp/wp-content/themes/phila.gov-theme/partials/departments/phila_staff_directory_loop.php

https://www.wrike.com/open.htm?id=1214379773

"translate=no" added to staff name

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php

https://www.wrike.com/open.htm?id=1241659362

required key added to date for lat updated

---

wp/wp-content/themes/phila.gov-theme/partials/departments/phila_staff_directory_loop.php

https://www.wrike.com/open.htm?id=1214379773

Translating staff name

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-site-wide-alert.php

https://www.wrike.com/open.htm?id=1285187721

Required fields for sitewide alerts

---

wp/wp-content/themes/phila.gov-theme/css/scss/_card.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

https://www.wrike.com/open.htm?id=1266810631

fix: Program tiles width fix

---

wp/wp-content/themes/phila.gov-theme/partials/resource-list.php

https://www.wrike.com/open.htm?id=1267617663

fix: Collection page heading fix

---

wp/wp-content/themes/phila.gov-theme/partials/resource-list.php

https://www.wrike.com/open.htm?id=1267617663

Collection page heading fix

---

wp/wp-content/themes/phila.gov-theme/partials/departments/phila_call_to_action_multi.php
wp/wp-content/themes/phila.gov-theme/partials/resource-list.php

https://www.wrike.com/open.htm?id=1214425890

Remove hr tag from resource cards

---

wp/wp-content/themes/phila.gov-theme/css/scss/_panel.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json
wp/wp-content/themes/phila.gov-theme/partials/content-custom-additional.php

https://www.wrike.com/open.htm?id=1240439124

fix: Related content visual bug

---

wp/wp-content/themes/phila.gov-theme/functions.php

This is an optimization of one of the SQL queries that was stalling out the server. Now I must test it to see if it resolves the slowdown or not.

sql fix attempt

---

wp/wp-content/db.php

Adding db.php to wp/wp-content to use the hyperDB plugin

added db.php for HyperDB

---

wp/wp-content/db.php

This should fix the scraper issue.

adding hyper DB to prod

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php

Remove hidden

---

wp/wp-content/themes/phila.gov-theme/css/scss/_accordion.scss

added padding to accordion 
Wrike ticket: https://www.wrike.com/open.htm?id=1538893923

Fix accordion spacing

---

wp/wp-content/plugins/phila.gov-customization/admin/admin-documentation.php

wrike ticket:
https://www.wrike.com/open.htm?id=1653529094

Docs update wp resource hub

---

package-lock.json
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/document-finder.php

corrected pagination and search for wrike tickets:
https://www.wrike.com/open.htm?id=1647235094
https://www.wrike.com/open.htm?id=1363703786

corrected pagination in php file

---

package-lock.json
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/document-finder.php

move changes into production for Wrike tickets:
https://www.wrike.com/open.htm?id=1363703786
https://www.wrike.com/open.htm?id=1647235094

Fix pagination php

---

wp/wp-content/themes/phila.gov-theme/css/scss/modules/_hero-header.scss

updated css to correct duplicate images for department pages. 
Wrike ticket: https://www.wrike.com/open.htm?id=1534371773

Fix hero images mobile

---

wp/wp-content/themes/phila.gov-theme/css/scss/_button.scss
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/full-width-call-to-action.php

for wrike ticket: https://www.wrike.com/open.htm?id=1623437508

Fix full width cta padding ctr

---

wp/wp-content/themes/phila.gov-theme/css/scss/base/_global-nav.scss

corrected display for translations menu

---

wp/wp-content/themes/phila.gov-theme/single-department_page.php
wp/wp-includes/post.php

Reverts CityOfPhiladelphia/phila.gov#2328

Revert "refactor: Fix brittle logic on Mayor's page"
