CityOfPhiladelphia/phila.gov

composer.json

Versions since 0.9.6 use new restrictions on media links that break our media library. We'll have to test new uploads and potentially modify the db before upgrading to current.

Downgrade amazon-s3-and-cloudfront

---

nginx/conf.d/fastcgi_cache.conf

The former value of 100m was greater than the /tmp directory in which
/var/run/nginx-cache was kept.

Limit wordpress fastcgi cache to 10m

---

wp/wp-content/themes/phila.gov-theme/functions.php

phila_get_dept_contact_blocks() checks if the page is categorized properly (only 1 category), if not display the uncategorized sidebar as the contact block.

Condition for displaying uncategorized contact block as default

---

scripts/install.sh

Seeing this error in deploy at private plugins step:
```
Abort class-pclzip.php : Missing zlib extensions
```

Include php7.0-zlib for unzipping plugins

---

wp/wp-content/plugins/phila.gov-customization/admin/admin-documentation.php
wp/wp-content/plugins/phila.gov-customization/index.php

- Creates a Dashboard menu item for documentation specific to managing content in our WordPress install. Temporarily named "Alpha Docs", but this should change when leaving the alpha stage.
- Adds our Alpha-specific MailChimp Docs

Adds initial Alpha Docs menu item and content

---

wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/header.php

Noticed a few minor issues while running the alpha homepage through the W3C Validator. 
- Closes open paragraph tag
- Add alt tag to logo (w/ appropriate content)

Corrects minor markup errors on front-page and header

---

wp/wp-content/themes/phila.gov-theme/single-department_page.php

This will allow pages that are private or in draft mode to function the way they would if they were live on the site.

Department pages of any status can be included in first-child redirects

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/content-feedback.php

This PR applies the new function in the content-feedback partial solving problems with special characters in friendly names of categories (example: Mayor's Office vs. mayor)

Add util function to get current cat slug

---

wp/wp-content/plugins/phila.gov-customization/public/class-phila-gov-site-wide-alert-rendering.php

Abbreviate months with greater that 5 letters.

Apply AP style date formatting to alerts

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/blogs.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/notices.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/press-releases.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

Replaces references to the `alternate` class with `contrast` across department single-on-site-content and shortcodes

Replace .alternate with .contrast

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-filter-post-type-links.php
wp/wp-content/plugins/phila.gov-customization/public/modify-post-type-links.php

Changes behavior when multiple categories are added to an item. Instead of assigning the last chosen category, use the first alphabetically.

Use array_shift instead of array_pop

---

nginx/conf.d/fastcgi_cache.conf

Set a `max_size=90m` to alleviate errors related to the fastcgi cache filling up.
We may want to change the cache dir from `/var/run/nginx-cache` to `/var/cache/nginx/fastcgi_temp/`, but for now this should keep us from hitting 100m with room to spare.
Thanks @gsf for the advice

Set a fastcgi_cache_path max_size

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-templates.php
wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js

* Add metadata to department pages to define homepage status.
* Check if page uses the one-page department template and automatically assign homepage status.

Homepage toggler

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-call-to-action-multi.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-custom-text-multi.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-custom-text.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-department-homepage.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-featured-pages.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-get-involved.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-hero-header.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-list-items.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php

This PR cleans up a few issues with the Department and Program & Initiative templates created during the sprint for MOE
- Better checking to make sure all necessary vars are declared before creating `row`s
- Consolidate repeated code in reusable partials 
- Where possible we intend to use `!empty()` instead of `$var != ''`, or `!$var ==''` when checking if a var is not empty
- Correct some errors in 1/2 x 1/2 column rows
- Some general markup clean up

General Cleanup

---

scripts/unison-build.sh

This script is not part of the automated deploy but rather, used to build a new version of Unison.
The script wasn't functioning properly because the source changed the name of the file it extracted to. Script has been updated.
Additionally, we've generated a new build of the latest stable version of Unison, v 2.48.4, and uploaded to the expected location in S3.

Update unison-build.sh to adjust for new path

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_panel.scss
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Allows user to enter _both_ wysiwyg content and address per heading area in "How to Pay" section
* Apply `the_content` filter to all fields with multi-line display
* Corrects "mil" to "mills"

Tax detail field tweaks

---

wp/wp-content/plugins/phila.gov-customization/public/class-content-collection-walker.php

* `Content_Collection_Walker` had been using `get_page_link`, but we are now using this walker on more than just Pages. Update it to `get_permalink` to fix.

Use get_permalink

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/blogs.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/press-releases.php
wp/wp-content/themes/phila.gov-theme/front-page.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-call-to-action-multi.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-department-homepage.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-row-two.php
wp/wp-content/themes/phila.gov-theme/single-event_page.php

This PR adds the blue outlined-arrow style to the the "See all" links being generated in the following locations.
**Shortcodes**
- blogs.php
- news.php
- press-releases
**Other**
- front-page.php (news area)
**Templates/Partials**
- content-call-to-action-multi.php
- content-department-homepage.php
- content-programs-initiatives.php
- content-row-two.php (calendar/events)
- single-event_page.php

Apply outlined-arrow style to "See all" links site-wide

---

wp/wp-content/plugins/phila.gov-customization/public/shortcodes/callout.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php

- Convert callout.php to an enclosed shortcode. 
- Sanitize `$content` with `wp_kses()` (allowing only `a`, `br`,`em`,`strong` elements)

Enclosed callout shortcode

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php

This fixes a problem where some users with access to multiple departments were inadvertently removing the parent page for nested department pages. 
The query to hide inaccessible categories from the Parent attribute dropdown was only reading the first category in the array, instead of the entire array.

Add pages user should not have access to to exclude list

---

scripts/predeploy.sh

Hopefully, prevent user input from interrupting predeploy.

Add "noninteractive" in case user input is required

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/tax-detail-fields.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/taxes/content-tax-detail.php

* Create admin fields for collecting changing tax information. 
* To be used when details about a tax are changing to give notice to users that there will be (and subsequently has been) a change. 
* Update `phila_wysiwyg_options_basic` with parameter to change height of editor when reused.

Include callouts

---

wp/wp-content/themes/phila.gov-theme/functions.php

Standardize on `$service_effective_end`, regardless of date or datetime input to determine if service update is valid.

Remove expression matching mdY. Use current_time instead

---

wp/wp-content/themes/phila.gov-theme/functions.php

Ensure a published service update doesn't appear if the time stamp is not valid.

Check start time before rendering active service update

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

- Corrects display of connect block if no phone or fax is entered. 
- Adds option to render "see all" connect link.
Users were not correctly identifying who they were calling from a single contact number. This solution gives users the ability to see a full list of potential contact options, hopefully mitigating incorrect phone calls.

Connect hotfix

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php

Allow category override on Staff pages to account for multiple category assignment.
Adds new phila standard metabox for category selection, `phila_metabox_category_single_select`.

Staff hotfix

---

wp/wp-content/themes/phila.gov-theme/css/scss/_swiftype.scss
wp/wp-content/themes/phila.gov-theme/js/dev/search.js

If you search an address on beta.phila.gov, the website detects that it's an address and lets you forward your search to property. [example](https://beta.phila.gov/search/#stq=1234%20market). But the OPA API is deprecated; it should use AIS.
@tswanson or @rbrtmrtn is this API key okay, or should we use a unique one?
@kdemi I haven't tested this; can you test before merging?

Address search: Use AIS instead of OPA API

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-documents.php
wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/themes/phila.gov-theme/templates/documents.php

* Correct rendering issue with some document pages
* Remove `document_type`  taxonomy
Change document page date workflow to the following: 
* Date is automatically set to date the item was uploaded.
* If the uploaded date is not the release date, allow for per-item date setting.
* If all the documents on the page should have the same release date, override the settings above and use global page date.

Document pages

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-role-administration.php

Give users who don't have access to post content (subscribers) the ability to get "credit" for what they have written. Future changes could include a custom role that does the same thing, in the event that we actually do something with subscriber user profiles.

Add subscribers to admin author list

---

nginx/nginx.conf

Set static sever_name to prevent HTTP Host header attacks.

Set static server_name

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

Long email address were breaking in awkward places when in the context of the connect box, or leadership displays. This adds a utility function to include a <wbr> tag around the second half of email address, allowing them to line-wrap nicely in newer browsers.

Create utility function to break long emails on @

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php

* Allow editors to see the "text" tab in the custom content section of department homepages. 
* Remove old variables that are no longer used.

Add text option back to wysiwyg

---

wp/wp-content/themes/phila.gov-theme/css/scss/beta/_inside-border.scss

* Overrides column padding to allow for full-width hover states. Allows for vertical padding in connect boxes.

Only remove right & left padding

---

wp/wp-content/plugins/meta-box/inc/interfaces/storage.php
wp/wp-content/plugins/meta-box/inc/storage-registry.php
wp/wp-content/plugins/meta-box/inc/storages/post.php
wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/meta-boxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/v2-departments.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/news.php
wp/wp-content/plugins/phila.gov-customization/public/shortcodes/press-releases.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-staff-directory.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

* Creates ability to override or add more categories to blog, news, or press release displays. This means any department can pull in items from any other department, if they chose to. Especially useful for departments that oversee other departments. 
* Update metabox to 4.11.3

Category selection

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-custom-post-types.php
wp/wp-content/plugins/phila.gov-customization/admin/rest-addtions.php
wp/wp-content/plugins/phila.gov-customization/index.php

* Adds `phila_page_icon`, specifically in use on service pages to rest API. This will allow us to recreate the service mega menu.

Rest api additions

---

nginx/server.d/csp.conf

This will remove  the Content Security Policy warning that appears on all pages.
```
The Content Security Policy 'default-src https: data: 'self' 'unsafe-inline' 'unsafe-eval'; report-uri' was delivered in report-only mode, but does not specify a 'report-uri'; the policy will have no effect. Please either add a 'report-uri' directive, or deliver the policy via the 'Content-Security-Policy' header.
``` 
* Allows images from all sources
* Essentially lists all urls from which we draw resources, including cdns.

More explicit Content Security Policy

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/content-list-featured-image.php

To prepare for more image centric news and events, increase the size of medium images. Allow cropping to get the exact dimensions, 700px x 400px. Add medium size to list of possible fallback image sizes.

Larger images

---

wp/wp-content/themes/phila.gov-theme/js/dev/hashchange-check.js

Eventually, we'll switch to [uglify-es](https://www.npmjs.com/package/uglify-es) or something similar.

Until uglifyjs is swapped out, use var instead of const

---

wp/wp-content/themes/phila.gov-theme/single-department_page.php

Allow redirects at the department landing level, but only when the following is true:
* There is nothing in the wysiwyg 
* The page template is department_page (i.e. it hasn't been changed)
* It's not a grandchild

Add redirects back, but allow for no redirects in specific cases

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-calendar-helper.php
wp/wp-content/plugins/phila.gov-customization/index.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

Creates a check for Simple Calendar, allowing Admins to copy a "Master" calendar's template onto any other calendar template they choose. Thanks to @alejandroxlopez for the idea and a proof of concept!
Once a "Master" calendar has been defined, all calendars inheriting the master will be automatically updated with the calendar layout and metafields, with the exception of:
* Google calendar ID
* Search queries
* Grouped calendar data
* List range type (to allow for "full" calendar views)
This can be extrapolated on for grid views in the future, if necessary.

Calendar plugin

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js
wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js

* Ensure users who aren't admins or editors don't see action guides without explicit permission

Correct action guide role display

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/header.php

* Move check for post type out of `phila_get_item_meta_desc()` to prevent duplication of meta descriptions on pages with lists of meta descriptions.

Correct meta desc

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-admin-templates.php

Trello issue: When "Staff" template is selected, add note about where in the admin to add new staff members.
The message is applied to the new and old staff directory template.
Moved this fix to its own branch.

staff template note

---

wp/wp-content/plugins/phila.gov-customization/public/class-phila-document-controller.php
wp/wp-content/themes/phila.gov-theme/css/scss/_table.scss
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Publications.vue
wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

* Adds department pages with the document finder template to documents and forms search.
* Cleans up implementation to add sort by date, and filters existing list instead of forcing new API call.
* Corrects "reset" to actually reset the data.
* Adds sortable table headers.

Document landing

---

wp/wp-content/plugins/phila.gov-customization/admin/class-phila-gov-admin-menu.php
wp/wp-content/themes/phila.gov-theme/css/scss/_programs-initiatives.scss
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/js/vuesrc/Programs.vue
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/department-hero.php
wp/wp-content/themes/phila.gov-theme/partials/programs/header.php
wp/wp-content/themes/phila.gov-theme/single-department_page.php

Adds ability for admins to add menus to any item with a "homepage" template. Dismantles old system of category association and instead registers all homepage templates as a discrete menu location, allowing for more flexibility for future menus and especially while pages are being staged for changes.

Program menus

---

wp/wp-content/themes/phila.gov-theme/js/vuesrc/Events.vue

Allow the pre-filled or user-entered date range to limit number of events displayed. 100 events is the api default.

Remove maxResults on filtered events view

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin.js

Setting the typenow variable causes non-admins to experience editing + saving issues.

Remove var

---

nginx/server.d/robots.conf

I'm not 100% sure about this but I googled it and everything I found suggests this would be the right syntax, e.g.:
- http://blog.tcs.de/serve-robots-txt-inline-in-nginx/
- https://alanthing.com/blog/2017/05/15/robots-dot-txt-disallow-all-with-nginx/

Fix robots.txt disallow rule

---

wp/wp-content/themes/phila.gov-theme/package-lock.json
wp/wp-content/themes/phila.gov-theme/package.json

The postbuild task was failing on a fresh install saying `postcss` was not available. The [`postcss` readme](https://github.com/postcss/postcss#npm-run--cli) points to [`postcss-cli`](https://github.com/postcss/postcss-cli) for CLI usage. Not sure how this has worked all this time but my only guess is that `postcss-cli` is installed globally on the AMI? :shrug:
Let me know if I've misunderstood how this works.

Use postcss-cli instead of postcss

---

scripts/deploy.sh

When new production machines get created, they'll start with the 8M defualt, so revert the replacement to 8, and set to a new max of 1000

Reset post_max_size

---

wp/wp-content/plugins/phila.gov-customization/admin/js/admin-department-author.js
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/departments/v2/content-connect.php

Correct admin issue where "post" template is automatically selected when a user with permissions to multiple post types edits existing content. 
Add new field for multiple phone numbers in a connect box.

Phone connect field + admin bugfix

---

wp/wp-content/plugins/duplicate-and-merge-posts-1.3.0/admin/duplicate-post.php

Prevents post meta from repeating when the field IDs are the same.

Fix postmeta fields for related content sections

---

wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/inc/breadcrumbs.php
wp/wp-content/themes/phila.gov-theme/partials/programs/header.php
wp/wp-content/themes/phila.gov-theme/single-department_page.php
wp/wp-content/themes/phila.gov-theme/templates/single-on-site-content.php

Ensure hero headers are appearing in the correct locations. Fixes warning in `page with association` twitter images.

Correct header on transition pages

---

wp/wp-content/plugins/phila.gov-customization/admin/settings/phila-gov-settings.php

Associated with this commit rendering the exception as html https://github.com/CityOfPhiladelphia/trashday-v2/commit/69cc0f46e22771c498e7e24653d9375429ecd964

exception as wysiwyg

---

wp/wp-content/themes/phila.gov-theme/partials/programs/header.php
wp/wp-content/themes/phila.gov-theme/single-department_page.php

Currently subpages with association are a template the users selects manually and a different header is applied only to that page. This PR checks if a child of a subpage with association has a parent of that template type, and if so, it applies the header from the parent page, instead of it's grandparent page (which would be the standard department or program header). This only works one level deep, currently. 
```
Parent page - department homepage
-- child page - subpage with association header 
---- grandchild page - now gets subpage with association header 
----- great grandchild page -  would revert to department homepage header
-- regular child page -  no change
```

Allow subpage with association to have one level deep of children

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-metaboxes.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-row-select-options.php
wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
wp/wp-content/themes/phila.gov-theme/css/scss/_accordion.scss
wp/wp-content/themes/phila.gov-theme/partials/content-custom-prereq-row.php
wp/wp-content/themes/phila.gov-theme/partials/content-single-heading-group.php
wp/wp-content/themes/phila.gov-theme/partials/departments/content-programs-initiatives.php
wp/wp-content/themes/phila.gov-theme/partials/global/accordion.php

This PR does a couple of things:
- Hides the stepped content option for heading groups appearing on the "custom_content" template 
- Corrects the code so if we ever wanted that option back, it would work
- Removes very old 1/2 1/2 template options that are no longer in use 
Tested on the following service templates: 
- Default
- Default (2020)
- Generic (old default)
Also tested on program homepage template.

Adjust template for stepped content + clean up accordion rendering

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/full-width-call-to-action.php

this is a fix for this wrike ticket https://www.wrike.com/workspace.htm?acc=2747306#path=folder&id=432990175&c=board&vid=3978741&p=489051602&a=2747306&ot=771879604&so=10&bso=10&sd=0&f=&st=space-453350584

add link text to modals in full page call to action

---

wp/wp-content/themes/phila.gov-theme/partials/departments/v2/photo-callout.php

This removes an isset() on the photo value and replaces it with a "null" check. This should prevent warnings in dev and correctly display the image in production.

Correct image check

---

wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-post.php
wp/wp-content/themes/phila.gov-theme/functions.php
wp/wp-content/themes/phila.gov-theme/partials/errors/post-errors.php

The deprecated phila_author field needs to be hidden rather than removed. When its deleted, it returns a single string of the first item in the array of items that should be returned. 
ex returned when hidden
array(2) { [0]=> string(3) "180" [1]=> string(3) "304" }
ex returned when deleted
"180"

unlisted authors

---

wp/wp-content/themes/phila.gov-theme/js/dev/phila-gov.js

Prevents on click event menu dropdown on desktop items when translation menu is clicked. 
https://www.wrike.com/workspace.htm?acc=2747306#folder/432990175/board?overlayEntityId=1087205364&sortOrder=10&spaceId=453350584&viewId=3978741

stops on click within translations menu

---

wp/wp-content/themes/phila.gov-theme/single-department_page.php
wp/wp-includes/post.php

Currently, we apply the special 2024-redesign template by checking the post_id. This is brittle because the page id can vary across environments. 
This fix does the same check by matching against the post_name (which in this case should be 'mayor'.) That value seemed like the most intuitive and also stable for our purposes. 
To accomplish this, I added a method `wp_get_post_parent_name` into `post.php` which mirrors the method above it, `wp_get_post_parent_id`.

refactor: Fix brittle logic on Mayor's page
